# docker-compose.yml

version: "3.3"

services:
  app:
    build:
      context: .
    container_name: django-server-container
    restart: always
    volumes:
      - static-data:/vol/static
      - media-data:/vol/media

  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-data:/vol/static
      - media-data:/vol/media
    container_name: nginx-server-container
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'qpoll_db_password229'  
      MYSQL_DATABASE: 'qpoll_db'
      MYSQL_PASSWORD: qpoll_db_password229

volumes:
  static-data:
  media-data:
