name: Deploy Docker Container

on:
  push:
    branches:
      - back-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          source: "."
          target: "/home"

      - name: Execute docker commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            docker stop django-server-container 2> /dev/null || true
            docker rm django-server-container 2> /dev/null || true
            docker stop nginx-server-container 2> /dev/null || true
            docker rm nginx-server-container 2> /dev/null || true
            apt-get clean
            docker system prune -f > /dev/null 2>&1
            cd /home/db
            docker-compose up -d
            cd /home/server
            docker-compose up -d --build
