name: Deploy Docker Container

on:
  push:
    branches:
      - back-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 89.111.155.6
        username: root
        password: H4b9hpYG4N44R5Gh
        port: 22
        source: "."
        target: "/home"
        
    - name: Execute docker commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 89.111.155.6
        username: root
        password: H4b9hpYG4N44R5Gh
        port: 22
        script: |
          cd /home/server
          if [ -d "app" ]; then
            rm -rf app
          fi
          mkdir app
          cd app
          mkdir static
          cd ..
          cd ..
          docker build -t django-image .
          docker run -d --name django-image


        
      
        # uses: appleboy/scp-action@v0.1.2
        # with:
        #   host: 89.111.155.6
        #   username: root
        #   port: 22
        #   key: ${{ secrets.SERVER_SSH_KEY }}
        #   source: "."
        #   target: "/home/app"

      # - name: SSH into server and build Docker image
      #   uses: appleboy/ssh-action@v0.1.2
      #   with:
      #     host: 89.111.155.6
      #     username: root
      #     port: 22
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /home/app/server
      #       docker build -t django-image .

      # - name: SSH into server and start Docker container
      #   uses: appleboy/ssh-action@v0.1.2
      #   with:
      #     host: 89.111.155.6
      #     username: root
      #     port: 22
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker stop django-image || true
      #       docker rm django-image || true
      #       docker run --name django-image -d django-image
