name: Deploy Front-end to Server

on:
  push:
    branches:
      - front-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print current working directory
        run: pwd
      - name: List all files in the directory
        run: ls -la

      - name: Set permissions for all files
        run: sudo chmod -R 777 client/.scannerwork
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              
      - uses: actions/checkout@v4
      - name: Check test status
        id: check_test_status
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests passed!"
            exit 0
          else
            echo "Tests failed!"
            exit 1
          fi

      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          source: "."
          target: "/home"

      - name: Execute docker commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            cd /home/client
            echo 'VITE_BASE_URL=http://${{ secrets.SERVER_HOST }}' > .env
            cd deploy
            docker stop my-frontend-app-container || true
            docker rm my-frontend-app-container || true
            docker-compose up -d --build
